name: appxemphim
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  dio: ^5.4.0
  carousel_slider: ^4.2.1
  dropdown_button2: ^2.3.8
  shared_preferences: ^2.2.2
  http: ^0.13.3
  video_player: ^2.8.6
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/files/
    - assets/images/MainPage/
    - assets/images/MovieList/
    
